# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [2]:
import numpy as np

In [3]:
# creating a 1d array
arr_1d= np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [4]:
#creating a 2d array
arr_2d= np.array([[1,2],[1,5]])
arr_2d

array([[1, 2],
       [1, 5]])

In [5]:
# creating a 3d array
arr_3d=np.array([
    [[1,2,3],[5,6,3]],
    [[3,2,4],[3,4,5]],
    [[1,9,0],[2,3,5]],
])
arr_3d

array([[[1, 2, 3],
        [5, 6, 3]],

       [[3, 2, 4],
        [3, 4, 5]],

       [[1, 9, 0],
        [2, 3, 5]]])

#INDEXING AND SLICING

In [6]:
arr_2d

array([[1, 2],
       [1, 5]])

In [7]:
arr_2d[1][1]

5

In [8]:
arr_2d[0,1]

2

In [9]:
#slicing a 2d array
arr_2d[1:,0]

array([1])

In [10]:
#indexing a 3d array
arr_3d


array([[[1, 2, 3],
        [5, 6, 3]],

       [[3, 2, 4],
        [3, 4, 5]],

       [[1, 9, 0],
        [2, 3, 5]]])

In [11]:
arr_3d[1,1,2]

5

In [12]:
arr_2d[1:,0:1]

array([[1]])

In [13]:
#slicing a 3d array
arr_3d[0:2,0:2,0:]

array([[[1, 2, 3],
        [5, 6, 3]],

       [[3, 2, 4],
        [3, 4, 5]]])

In [14]:
arr_1dcopy = arr_1d.copy()

In [15]:
arr_1d + 7

array([ 8,  9, 10, 11, 12])

In [16]:
my_arr = np.arange(0,20,2)
my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# The code below will add corresponding elements of two arrays
my_arr + my_arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [18]:
my_arr + 5

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

# CONDITIONAL FILTERING AND BOOOLEAN MASKING

In [19]:
arr_2d>4

array([[False, False],
       [False,  True]])

In [20]:
arr_2d[arr_2d>4]

array([5])

& signifies 'and'

| signifies 'or'

~ signifies 'not'

In [21]:
arr_3d[(arr_3d >= 5) & (arr_3d <=8)]

array([5, 6, 5, 5])

In [22]:
arr_3d[(arr_3d >= 5) | (arr_3d <=8)]

array([1, 2, 3, 5, 6, 3, 3, 2, 4, 3, 4, 5, 1, 9, 0, 2, 3, 5])

In [23]:
arr_3d[~(arr_3d >= 5)]

array([1, 2, 3, 3, 3, 2, 4, 3, 4, 1, 0, 2, 3])

In [24]:
np.matmul([[2,3], [4,5]], [[1,2], [0,5]])

array([[ 2, 19],
       [ 4, 33]])

In [25]:
np.matmul([2,3, 4,5], [1,2, 0,5])

33

In [26]:
#The code below will multiply corresponding elements of two arrays
my_arr * my_arr

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

In [27]:
mat_1= [[1,2,3],[4,5,6],[7,8,9]]
mat_2= [3,5,10]

In [28]:
# we can do scalar multiplication of two arrays which multiplies corresponding elements of both arrays
mul= np.array(mat_1)*np.array(mat_2)
mul

array([[ 3, 10, 30],
       [12, 25, 60],
       [21, 40, 90]])

In [29]:
# the dot function does the vector or dot product of two arrays; 
#note how this is different from scalar product
mat1=np.array(mat_1)
mat2=np.array(mat_2)
matmul1=mat1.dot(mat2)
matmul1

array([ 43,  97, 151])

In [30]:
matmul2=mat2.dot(mat1)
matmul2

array([ 93, 111, 129])

In [31]:
# The matmul function in numpy also does the vector product of two arrays
np.matmul(mat1,mat2)

array([ 43,  97, 151])

In [32]:
np.matmul(mat2,mat1)

array([ 93, 111, 129])

In [33]:
# The code below finds the cube of each element in the array
my_arr**3

array([   0,    8,   64,  216,  512, 1000, 1728, 2744, 4096, 5832],
      dtype=int32)

In [34]:
# The code below finds the square root of each element in the array
np.sqrt(my_arr)

array([0.        , 1.41421356, 2.        , 2.44948974, 2.82842712,
       3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069])

# NumPy Indexing and Selection

This deals with how to select elements or groups of elements from an array.

In [35]:
my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
my_arr[3]

6

In [37]:
#to get values within an index range:
my_arr[2:5]

array([4, 6, 8])

In [38]:
##change values with an index range:
my_arr[2:5] = 50
my_arr

array([ 0,  2, 50, 50, 50, 10, 12, 14, 16, 18])

In [39]:
my_arr= np.arange(0,20,2)

In [40]:
my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
##to get a slice of the array:
slice_of_my_arr= my_arr[0:5].copy()
#slice_of_my_arr= my_arr[0:5]
slice_of_my_arr

array([0, 2, 4, 6, 8])

In [42]:
slice_of_my_arr[:]=100
slice_of_my_arr

array([100, 100, 100, 100, 100])

In [43]:
##changes we made to array slice will also appear in original array
my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Indexing a 2D array (matrices)

In [44]:
my_mat = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
my_mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [45]:
#Indexing row
my_mat[1]

array([20, 25, 30])

In [46]:
#indexing column
my_mat[1,2] 

30

In [47]:
my_mat[1][2]

30

In [48]:
# Getting individual element value
my_mat[1][0]

20

In [49]:
my_mat[1,0]

20

In [50]:
my_mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [51]:
# 2D array slicing

my_mat[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [52]:
# 2D array slicing

my_mat[:2, 1:]

array([[10, 15],
       [25, 30]])

## Selection

We can use brackets for selection based on comparison of elements

In [53]:
new_arr= np.arange(0,40,5)
new_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [54]:
new_arr > 10

array([False, False, False,  True,  True,  True,  True,  True])

In [55]:
new_arr<20

array([ True,  True,  True,  True, False, False, False, False])

In [56]:
new_arr[new_arr<20]

array([ 0,  5, 10, 15])

In [57]:
k= 9
new_arr[new_arr<k]

array([0, 5])

# ASSIGNMENT

1.Explore any 10 array creation routines in numpy documenation and practice them

2.Explore any 10 array manipulation routines and practice them

In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print(flattened_arr)


[1 2 3 4 5 6]


In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = np.transpose(arr)
print(transposed_arr)


[[1 4]
 [2 5]
 [3 6]]


In [60]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)


[1 2 3 4 5 6]


In [61]:
arr = np.arange(9)
splitted_arr = np.split(arr, 3)
print(splitted_arr)


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [62]:
arr = np.array([1, 2, 3, 4, 5])
appended_arr = np.append(arr, [6, 7])
deleted_arr = np.delete(arr, [1, 2])
print(appended_arr)
print(deleted_arr)


[1 2 3 4 5 6 7]
[1 4 5]
