# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(0,20,2)
my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
# The code below will add corresponding elements of two arrays
my_arr + my_arr

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [4]:
my_arr + 5

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [5]:
np.matmul([[2,3], [4,5]], [[1,2], [0,5]])

array([[ 2, 19],
       [ 4, 33]])

In [ ]:
np.matmul([2,3, 4,5], [1,2, 0,5])

In [7]:
#The code below will multiply corresponding elements of two arrays
my_arr * my_arr

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324])

In [12]:
mat_1= [[1,2,3],[4,5,6],[7,8,9]]
mat_2= [3,5,10]

In [13]:
# we can do scalar multiplication of two arrays which multiplies corresponding elements of both arrays
mul= np.array(mat_1)*np.array(mat_2)
mul

array([[ 3, 10, 30],
       [12, 25, 60],
       [21, 40, 90]])

In [14]:
# the dot function does the vector or dot product of two arrays; 
#note how this is different from scalar product
mat1=np.array(mat_1)
mat2=np.array(mat_2)
matmul1=mat1.dot(mat2)
matmul1

array([ 43,  97, 151])

In [15]:
matmul2=mat2.dot(mat1)
matmul2

array([ 93, 111, 129])

In [ ]:
# The matmul function in numpy also does the vector product of two arrays
np.matmul(mat1,mat2)

In [ ]:
np.matmul(mat2,mat1)

In [ ]:
# The code below finds the cube of each element in the array
my_arr**3

In [ ]:
# The code below finds the square root of each element in the array
np.sqrt(my_arr)

# NumPy Indexing and Selection

This deals with how to select elements or groups of elements from an array.

In [16]:
my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
my_arr[3]

6

In [18]:
#to get values within an index range:
my_arr[2:5]

array([4, 6, 8])

In [19]:
##change values with an index range:
my_arr[2:5] = 50
my_arr

array([ 0,  2, 50, 50, 50, 10, 12, 14, 16, 18])

In [29]:
my_arr= np.arange(0,20,2)

In [30]:
my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
##to get a slice of the array:
slice_of_my_arr= my_arr[0:5].copy()
#slice_of_my_arr= my_arr[0:5]
slice_of_my_arr

array([0, 2, 4, 6, 8])

In [32]:
slice_of_my_arr[:]=100
slice_of_my_arr

array([100, 100, 100, 100, 100])

In [33]:
##changes we made to array slice will also appear in original array
my_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Indexing a 2D array (matrices)

In [34]:
my_mat = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
my_mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
#Indexing row
my_mat[1]

array([20, 25, 30])

In [41]:
#indexing column
my_mat[1,2] 

30

In [42]:
my_mat[1][2]

30

In [ ]:
# Getting individual element value
my_mat[1][0]

In [ ]:
my_mat[1,0]

In [43]:
my_mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [45]:
# 2D array slicing

my_mat[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [46]:
# 2D array slicing

my_mat[:2, 1:]

array([[10, 15],
       [25, 30]])

## Selection

We can use brackets for selection based on comparison of elements

In [47]:
new_arr= np.arange(0,40,5)
new_arr

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [48]:
new_arr > 10

array([False, False, False,  True,  True,  True,  True,  True])

In [49]:
new_arr<20

array([ True,  True,  True,  True, False, False, False, False])

In [50]:
new_arr[new_arr<20]

array([ 0,  5, 10, 15])

In [51]:
k= 9
new_arr[new_arr<k]

array([0, 5])