In [2]:
import numpy as np

In [3]:
d1 = np.array([4,7,4])

In [4]:
d2 = np.array([[3,2,1],[3,2,5]])

In [5]:
d2

array([[3, 2, 1],
       [3, 2, 5]])

In [6]:
d3 = np.array([[[3,1],[2,5],[5,6]],[[4,2],[6,9],[1,4]]])

In [7]:
d3

array([[[3, 1],
        [2, 5],
        [5, 6]],

       [[4, 2],
        [6, 9],
        [1, 4]]])

In [8]:
d1[-3:]

array([4, 7, 4])

In [9]:
d2

array([[3, 2, 1],
       [3, 2, 5]])

In [10]:
d2[0 , 0]

3

In [11]:
d2[0:2,0:2]

array([[3, 2],
       [3, 2]])

In [12]:
d3[0]

array([[3, 1],
       [2, 5],
       [5, 6]])

In [13]:
d3[0,1,0]

2

In [14]:
d3[1, 1:,0]

array([6, 1])

In [15]:
d1.shape

(3,)

In [16]:
d2.shape

(2, 3)

In [17]:
d3.shape
#meaning we have 2..... 3,2 matrix

(2, 3, 2)

In [18]:
d3.ndim
#tells you number of dimensions

3

In [19]:
d3.size

12

In [20]:
d1+ 5

#possible due to broadcasting

array([ 9, 12,  9])

In [21]:
d2 + np.array([1,7,5])

array([[ 4,  9,  6],
       [ 4,  9, 10]])

In [22]:
d2 + np.array([[1],[7]]).shape


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [ ]:
np.random.randint?

Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Outp

In [ ]:
np.random.seed(1)
np.random.randint(10,size=(2,3))

array([[5, 8, 9],
       [5, 0, 0]])

In [ ]:
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method

In [ ]:
np.random.rand(5,3)


array([[0.39658073, 0.38791074, 0.66974604],
       [0.93553907, 0.84631092, 0.31327352],
       [0.52454816, 0.44345289, 0.22957721],
       [0.53441391, 0.91396202, 0.45720481],
       [0.43069857, 0.93912779, 0.77838924]])

In [ ]:
np.random.randn(3,2)


array([[ 0.8858294 ,  0.63190187],
       [ 0.04026035, -0.90312288],
       [ 0.17532267,  0.19443089]])

In [ ]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
#reshape method allows you to change the dimension array
d2.shape

(2, 3)

In [ ]:
d2.reshape((2, 3,1))

array([[[3],
        [2],
        [1]],

       [[3],
        [2],
        [5]]])

In [ ]:
d3.shape

(2, 3, 2)

In [ ]:
d3.reshape((-1, 4))

array([[3, 1, 2, 5],
       [5, 6, 4, 2],
       [6, 9, 1, 4]])

In [ ]:
d1.sum()

15

In [ ]:
d2.sum()

16

In [ ]:
d2

array([[3, 2, 1],
       [3, 2, 5]])

In [ ]:
d2.sum(axis=0)

array([6, 4, 6])

In [ ]:
d1

array([4, 7, 4])

In [ ]:
np.max(d1)

7

In [ ]:
np.argmax(d1)
 

1

In [ ]:
np.argmin(d1)

0

In [ ]:
d1 > 5 

array([False,  True, False])

In [ ]:
d1[(d1 > 5) & (d1 != 7) ]

array([], dtype=int32)

assignment

In [ ]:
e1 = np.full(2,2)
e1

array([2, 2])

In [ ]:
tu = [4,5]

In [ ]:

e2 = np.asanyarray(tu)

In [ ]:
e2

array([4, 5])

In [ ]:
e3 = np.ascontiguousarray(e2)

In [ ]:
e3

array([4, 5])

In [ ]:
e4 = np.mgrid[0:5, 0:5]
e5 = np.mgrid[-1:1:5j]


In [ ]:
e4

array([[[0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4]],

       [[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]])

In [ ]:
e5

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [ ]:
e6 = np.moveaxis(e4, 0, -1)

In [ ]:
e6

array([[[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4]],

       [[1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4]],

       [[2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4]],

       [[3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4]],

       [[4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4]]])

In [ ]:
e7 = np.concatenate((e3, e2,e3), axis=0)

In [ ]:
e7

array([4, 5, 4, 5, 4, 5])

In [ ]:
e8 = np.split(e7, 3)

In [ ]:
e8

[array([4, 5]), array([4, 5]), array([4, 5])]

In [ ]:
e9 = np.flip(e6, 0)

In [ ]:
e9

array([[[4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4]],

       [[3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4]],

       [[2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4]],

       [[1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4]],

       [[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4]]])

In [ ]:
e10 = np.column_stack((e6,e9))

In [ ]:
e10

array([[[0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4]],

       [[1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4]],

       [[2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4],
        [2, 0],
        [2, 1],
        [2, 2],
        [2, 3],
        [2, 4]],

       [[3, 0],
        [3, 1],
        [3, 2],
        [3, 3],
        [3, 4],
        [1, 0],
        [1, 1],
        [1, 2],
        [1, 3],
        [1, 4]],

       [[4, 0],
        [4, 1],
        [4, 2],
        [4, 3],
        [4, 4],
        [0, 0],
        [0, 1],
        [0, 2],
        [0, 3],
        [0, 4]]])

numpy class day2

In [ ]:
a = np.array([3,2,5,6,7,8,9])

In [ ]:
d = a.copy()

In [ ]:
d

array([3, 2, 5, 6, 7, 8, 9])

Pandas

In [23]:
import pandas as pd

In [24]:
pd.Series(data=[4,6,8,9])

0    4
1    6
2    8
3    9
dtype: int64

In [25]:
s1 = pd.Series(data=[4,6,8,9],index=['a','b','c','d'], dtype="float32")

In [26]:
s1

a    4.0
b    6.0
c    8.0
d    9.0
dtype: float32

In [27]:
s1['c']

8.0

In [28]:
s1.loc['b']

6.0

In [29]:
s1.iloc[1]

6.0

In [30]:
s1.iloc[0:2]

a    4.0
b    6.0
dtype: float32

In [31]:
s1.loc['a':'c']

a    4.0
b    6.0
c    8.0
dtype: float32

In [ ]:
s1.values

array([4., 6., 8., 9.], dtype=float32)

In [ ]:
s1.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
ed = [2,3,4,5,6,7,8,9] * 3

In [ ]:
ed

[2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows 

In [32]:
df = pd.DataFrame([[8,4,1,6],[7,9,0,8],[2,4,5,7]],index=[1,2,3],columns=['A','b','c','d'])

In [33]:
df[['A','b']]

A  b
1  8  4
2  7  9
3  2  4

In [34]:
df.shape

(3, 4)

In [ ]:
df.loc[2:3,["A",'b']]

A  b
2  7  9
3  2  4

In [ ]:
df >3

A     b      c     d
1   True  True  False  True
2   True  True  False  True
3  False  True   True  True

In [ ]:
df[df>3]

A  b    c  d
1  8.0  4  NaN  6
2  7.0  9  NaN  8
3  NaN  4  5.0  7

In [ ]:
df.drop('b',axis=1,inplace= True)

In [ ]:
df

A  c  d
1  8  1  6
2  7  0  8
3  2  5  7

In [ ]:
df.reset_index(drop = True)

A  c  d
0  8  1  6
1  7  0  8
2  2  5  7

In [ ]:
df.set_index('A')

c  d
A      
8  1  6
7  0  8
2  5  7

In [ ]:
df = pd.DataFrame([[2,4,10],[1,np.nan,np.nan],[5,np.nan,np.nan]],columns=['x','y','z'])
df

x    y     z
0  2  4.0  10.0
1  1  NaN   NaN
2  5  NaN   NaN

In [ ]:
df.dropna()

x    y     z
0  2  4.0  10.0

In [ ]:
df.dropna(axis=1)


x
0  2
1  1
2  5

In [ ]:
df.dropna(axis=1 ,thresh=2)


x
0  2
1  1
2  5

In [ ]:
df.fillna(7)

x    y     z
0  2  4.0  10.0
1  1  7.0   7.0
2  5  7.0   7.0

In [ ]:
df['y'] = df['y'].fillna(df['y'].mean())

In [ ]:
df

x    y     z
0  2  4.0  10.0
1  1  4.0   NaN
2  5  4.0   NaN

In [ ]:
df.shape

NameError: name 'df' is not defined

Assignmemt